source "https://rubygems.org"

gem "bootsnap", require: false
gem "faker", "~> 3.5", group: :development
gem "kamal", require: false
gem "kaminari"
gem "pg"
gem "puma", ">= 5.0"
gem "rails", "~> 8.0.2"
gem "solid_cable"
gem "solid_cache"
gem "solid_queue"
gem "sqlite3", ">= 2.1"
gem "thruster", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

gem "pg_search", "~> 2.3"
